# Generated by Django 5.2.8 on 2025-11-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactionproduct',
            name='item_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
