# Generated by Django 4.2.11 on 2025-11-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_transaction_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_refused',
            field=models.BooleanField(default=False),
        ),
    ]
